# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = false

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false

defaultBackgroundImage = "bck2.jpg" # used as default for background images 

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  homepageImage = "bck3.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts" 
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = true
  showSummary = true
  # sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email"]

[list]
  showHero = true
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[about]
description = "I am a highly responsible data professional with advanced analytical skills in **machine learning, data analytics, and statistical modeling**. With a strong academic foundation in geosciences and engineering, I specialize in transforming complex datasets into actionable insights through **Python, SQL, and data visualization**. My experience spans feature engineering, time-series analysis, and developing data-driven solutions across diverse fields. I am passionate about leveraging data to **optimize workflows and drive impactful decision-making**."
image = "icon2.jpg"

[skills]
categories = [
  { name = "Programming Languages", items = ["Python", "SQL", "Tableau"], icon='<svg class="w-8 h-8 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 100 100"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="8" d="M35.8 39.4 46.5 50 35.8 60.6m17.7 0H64.2m-39 17.8H74.8a7.1 7.1 0 0 0 7.1-7.1V28.7a7.1 7.1 0 0 0-7.1-7.1H25.2a7.1 7.1 0 0 0-7.1 7.1V71.3A7.1 7.1 0 0 0 25.2 78.4Z"/> </svg>'},
  { name = "Machine Learning", items = ["PyTorch", "Uncertainty Quantification", "Explainable AI", "Computer vision"], icon='<svg class="w-8 h-8 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 100 100"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="8" d="M21.4,13.3V29.6m-8.1-8.2H29.6m-4.1,49V86.7m-8.1-8.1H33.7M54.1,13.3l9.3,28L86.7,50,63.4,58.7l-9.3,28-9.3-28L21.4,50l23.4-8.7Z"/> </svg>'},
  { name = "Data Analysis", items = ["Statistical Analysis", "Data Visualization", "Time Series Analysis", "Feature Engineering"], icon='<svg class="w-8 h-8 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 100 100"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="8" d="M30.2,48,42.1,36.2,54,48,69.8,32.2M34.2,83.6,50,67.8,65.8,83.6M14.4,16.4H85.6m-67.2,0H81.6V63.8a3.9,3.9,0,0,1-3.9,4H22.3a3.9,3.9,0,0,1-3.9-4Z"/> </svg>' }
]
